In [1]:
# Tensors
# At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. 
import torch

In [2]:
# Number
t1 = torch.tensor(4.0)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
# Matrix
t3 = torch.tensor([[5., 6],
                  [7, 8], 
                  [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
# 3-dimensional array
t4 = torch.tensor([
   [[1, 2, 3],
    [3, 4, 5]],
   [[5, 6, 7],
    [7, 8, 9]]]) 

t4

tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])

In [7]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [8]:
t2.shape


torch.Size([4])

In [9]:
t3.shape

torch.Size([3, 2])

In [10]:
t4.shape

torch.Size([2, 2, 3])

In [11]:
# Tensor operations and gradients
# We can combine tensors with the usual arithmetic operations

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [12]:
# Arithmetic operations
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [13]:
# y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch unique is that we can automatically compute the derivative of y. 
#the tensors that have requires_grad set to True i.e. w and b. This feature of PyTorch is called autograd (automatic gradients).


In [14]:
# To compute the derivatives, we can invoke the .backward method on our result y.
y.backward()
# The derivatives of y with respect to the input tensors are stored in the .grad property of the respective tensors.

C:\Users\souha\anaconda3\lib\site-packages\torch\autograd\__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


In [15]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [16]:
# As expected, dy/dw has the same value as x, i.e., 3, and dy/db has the value 1. 
# Note that x.grad is None because x doesn't have requires_grad set to True.
#The "grad" in w.grad for example is short for gradient, which is another term for derivative. 
#The term gradient is primarily used while dealing with vectors and matrices.


In [17]:
# Tensor functions

# Apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors. 
# Let's look at some examples.

#1 Create a tensor with a fixed value for every element
t6 = torch.full((3,2),5)
t6

tensor([[5, 5],
        [5, 5],
        [5, 5]])

In [18]:
# Concatenate two tensors with compatible shapes

t7= torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  5.]])

In [19]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9589, -0.9589],
        [-0.9589, -0.9589],
        [-0.9589, -0.9589]])

In [20]:
# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9589, -0.9589]],

        [[-0.9589, -0.9589],
         [-0.9589, -0.9589]]])

In [21]:
# more Tensor Operations are available here: https://pytorch.org/docs/stable/torch.html . 

In [22]:
# Interoperability with Numpy

#Numpy is a popular open-source library used for mathematical and scientific computing in Python. 
# It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

# Pandas: for file I/O and data analysis
# Matplotlib: for plotting and visualization
# OpenCV: for image and video processing


In [25]:
import numpy as np
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [27]:
# We can convert a Numpy array to a PyTorch tensor using torch.from_numpy

y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [28]:
# Let's verify that the numpy array and torch tensor have similar data types.
x.dtype, y.dtype

(dtype('int32'), torch.int32)

In [23]:
#The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

# why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

#1) Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
#2) GPU support: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). 
    #Computations that might typically take hours can be completed within minutes using GPUs.